Skip to content
Navigation Menu

Code
Pull requests
Actions
Projects
Security
Insights
Creating a new workflow file in authenticator.cc
Breadcrumbsauthenticator.cc/.github/workflows
/
main.yml
in
master

Edit

Preview
Indent mode

Spaces
Indent size

2
Line wrap mode

No wrap
Editing main.yml file contents
1
Enter file contents here
Use Control + Shift + m to toggle the tab key moving focus. Alternatively, use esc then tab to move to the next interactive element on the page.
Use Control + Space to trigger autocomplete in most situations.
New File at / · MWcySecOps/authenticator.cc
